export const GET_WEATHER_FORECAST_SUCCESS = "GET_WEATHER_FORECAST_SUCCESS";
export const GET_WEATHER_FORECAST_LOADING = "GET_WEATHER_FORECAST_LOADING";
export const GET_WEATHER_FORECAST_FAIL = "GET_WEATHER_FORECAST_FAIL";
